#!/opt/local/bin/python
# vim: set fileencoding=utf-8 :

"""
Project Euler
Problem 012

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

           z: 12,2,,3,3,5,4,5,6,6,
 bigeerthanz: 12, 23,,5 ,6 

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

"""

def triangles():
    i = 1
    while True:
        yield i
        i += (i + 1)

def factors(num):
    factors = []
    for i in xrange(1,((num+1)/2)):
        if num % i == 0:
            factors.append(i)
            factors.append(num / i)
    return factors
    
    
    
print factors(16777215 * ( 16777215 + 1)/ 2)
    

biggest_numfactors = 0
for i in triangles():
    numfactors = len(factors(i))
    if numfactors > biggest_numfactors:
        biggest_numfactors = numfactors
        print "%s:" % i
        for factor in factors(i):
            print factor, 
        print
        print numfactors
    if numfactors > 500:
        print i
        for factor in factors(i):
            print factor, 
        print
        break




