#!/opt/local/bin/python

"""
Project Euler
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


"""

def fib_evens(biggest):
    """
    return even fib terms below biggest
    """
    prev = 1
    num = 2
    yield 2
    while num < biggest:
        new = prev + num
        prev = num
        num = new
        if num % 2 == 0:
            yield num


#for i in fib_evens(100):
#    print i,
print sum(fib_evens(4000000))
